# basic configuration
server:
  name: §aMC
# rabbitmq configuration
rabbitmq:
  uri: amqp://guest:guest@localhost:5672
# insert token to enable to builtin discord bot to also mirror chat to a discord channel
# this is only required once per network! the bot can be hosted standalone
discord_bot_token: 'token'
# chat channel configuration; the first channel is default for all players, regardless of the permission property
# each entry can be configured with all given properties (alias:string, formatters:obj, publish:bool and permission:string)
channels:
  # an example global channel, which is accessible throughout all servers
  - global:
      alias: g

      # these options are only relevant if 'discord_bot_token' is set
      # they can be applied to all channel configuration entries
      # the id of the discord channel to mirror this channel to
      discord_channel_id: 0
      # url of the webhook to use. leave blank to auto populate
      discord_webhook_url: ''
      # invite url to provide inside in-game chat
      discord_invite_url: ''
  # an example local channel, which will not be sent to rabbitmq
  - local:
      alias: l
      publish: false
  # an example staff channel, which requires permission 'chat.channel.staff' to join
  - staff:
      alias: s
      permission: chat.channel.staff
# formatter configuration; these formatters are applied in configured order to each message's content
formatting:
  # make URLs clickable todo: shouldn't this occur by default?
  urls:
    force_https: true
  # a markdown parser. supports features: 'bold', 'cursive', 'underline', 'strikethrough', 'hidden_links', 'verbatim'
  markdown:
    # disable some features
    disable:
      - hidden_links
    # convert verbatim markdown strings to obfuscated minecraft style
    verbatim_to_obfuscated: true
  # a regex replacer. each pattern match will be replaced with the string defined in the 'replace' property
  regex:
    case_insensitive: true # default
    patterns:
      - "(^| )n+[i1Ιιe]*[qg9]+[a4e3rh]+" # pattern for the n-word including leetspeak alternatives
      - "(^| )[a4]+[s5]{2,}(h+[o0]+[li17]+[e3]*)?" # pattern for 'ass' and 'asshole" including leetspeak alternatives
    replace: "$1[bad word]" # $1 to retain leading whitespace
    # requires BanMod: punishes occurrences with the given punishment expression
    punish-by: 'mute:5m'
  # changes the basic format of the message
  # "%player_name%" and "%message%" are special format strings that will be formatted using vanilla methods
  #scheme: "<%player_name%> %message%" # vanilla scheme
  scheme: "§7[%server_name%§7] §f%player_name%§f: %message%"
# compatibility layers configuration
compatibility:
  # enhanced listener compatibility mode
  # enable this only if you are experiencing issues with moderation plugins
  # enabling this will partially break clickable urls and similar features
  listeners: false
  # configure compatibility with AurionChat plugin
  # reference: https://github.com/Mineaurion/Aurionchat
  # this will convert ChatMod packets to AurionChat packets on the specified RabbitMQ uri
  # may be set to 'inherit' to use the main ChatMod RabbitMQ uri, a different RabbitMQ uri, or 'none' to disable
  aurionchat: none