name: ChatMod
version: '0.1.0'
description: Cross-server chat linker mod using RabbitMQ
main: com.ampznetwork.chatmod.spigot.ChatMod$Spigot
api-version: '1.18'
load: STARTUP
website: https://github.com/AMPZNetwork/ChatMod
depend:
  - LibMod
softdepend:
  - BanMod
  - PlaceholderAPI
libraries:
  # discord
  - 'net.dv8tion:JDA:5.2.2'
  - 'club.minnced:discord-webhooks:0.8.4'
  - 'com.kcthota:emoji4j:6.0'
commands:
  reload:
    description: Reloads Configuration
    permission: chatmod.reload
  status:
    description: Prints plugin and module status information
    permission: chatmod.status
  channel:
    aliases: ch
    description: Select Channel
    usage: channel <info/list/join/leave/spy> [channel]
  shout:
    aliases: sh
    description: Shout into a specific channel
    usage: shout <channel> <message>
    permission: chatmod.shout
permissions:
  chatmod:
    description: Root permission node
    default: false
    children:
      chatmod.reload:
        description: Permission for the /chatmod:reload command
        default: op
      chatmod.status:
        description: Permission for the /chatmod:status command
        default: op
      chatmod.shout:
        description: Permission for the /chatmod:shout command
        default: true
      chatmod.channel:
        description: Permission for the /chatmod:channel command
        default: true
        children:
          chatmod.channel.list:
            description: Permission for the /chatmod:channel list command
            default: true
          chatmod.channel.info:
            description: Permission for the /chatmod:channel info command
            default: true
          chatmod.channel.join:
            description: Permission for the /chatmod:channel join command
            default: true
          chatmod.channel.spy:
            description: Permission for the /chatmod:channel spy command
            default: op
            children:
              chatmod.channel.spy.auto:
                description: Permission for automatic spying on channels
                default: false
                children:
                  chatmod.channel.spy.auto.*:
                    description: Permission for automatic spying on all channels
                    default: op
      chatmod.format:
        description: Required for advanced formatting
        children:
          chatmod.format.italic:
            description: Required for using format codes for italic text
            default: true
          chatmod.format.bold:
            description: Required for using format codes for bold text
            default: true
          chatmod.format.strikethrough:
            description: Required for using format codes for strikethrough text
            default: true
          chatmod.format.hidden_links:
            description: Required for using hidden links
            default: op
