name: ChatMod
version: '0.1.0'
description: Cross-server chat linker mod using RabbitMQ
main: com.ampznetwork.chatmod.spigot.ChatMod$Spigot
api-version: '1.18'
load: STARTUP
website: https://github.com/AMPZNetwork/ChatMod
depend:
  - LibMod
commands:
  reload:
    description: Reloads Configuration
    permission: chatmod.reload
  channel:
    aliases: ch
    description: Select Channel
    usage: channel <info/list/join/leave/spy> <channel>
    permission: chatmod.selection
  shout:
    aliases: sh
    description: Shout into a specific channel
    usage: shout <channel> <message>
    permission: worldmod.selection
