name: ChatMod
version: '0.1.0'
description: Cross-server chat linker mod using RabbitMQ
main: com.ampznetwork.chatmod.spigot.ChatMod$Spigot
api-version: '1.18'
load: STARTUP
website: https://github.com/AMPZNetwork/ChatMod
depend:
  - LibMod
softdepend:
  - BanMod
  - PlaceholderAPI
libraries:
  - com.google.code.gson:gson:2.11.0
  - net.kyori:adventure-text-serializer-gson:4.17.0
  - net.kyori:adventure-text-serializer-plain:4.17.0
commands:
  reload:
    description: Reloads Configuration
    permission: chatmod.reload
  channel:
    aliases: ch
    description: Select Channel
    usage: channel <info/list/join/leave/spy> [channel]
  shout:
    aliases: sh
    description: Shout into a specific channel
    usage: shout <channel> <message>
    permission: chatmod.shout
permissions:
  chatmod:
    description: Root permission node
    default: false
    children:
      chatmod.shout:
        description: Permission for the /chatmod:shout command
        default: true
      chatmod.channel:
        description: Permission for the /chatmod:channel command
        default: true
        children:
          chatmod.channel.list:
            description: Permission for the /chatmod:channel command
            default: true
          chatmod.channel.info:
            description: Permission for the /chatmod:channel command
            default: true
          chatmod.channel.join:
            description: Permission for the /chatmod:channel command
            default: true
          chatmod.channel.spy:
            description: Permission for the /chatmod:channel command
            default: true
      chatmod.format:
        description: Required for advanced formatting
        children:
          chatmod.format.italic:
            description: Required for using format codes for italic text
            default: true
          chatmod.format.bold:
            description: Required for using format codes for bold text
            default: true
          chatmod.format.strikethrough:
            description: Required for using format codes for strikethrough text
            default: true
          chatmod.format.hidden_links:
            description: Required for using hidden links
            default: false